### ISSUE TITLE
Wrong thin version when trying to start sensu-api

### ISSUE THREAD

**Issue by cbrown2** [centos-opstools/opstools-ansible#98]
Hi,

Not sure if this belongs here or somewhere else but...

/usr/share/rubygems/rubygems/dependency.rb:296:in `to_specs': Could not find 'thin' (= 1.6.3) - did find: [thin-1.6.4] (Gem::LoadError)
        from /usr/share/rubygems/rubygems/dependency.rb:307:in `to_spec'
        from /usr/share/rubygems/rubygems/core_ext/kernel_gem.rb:47:in `gem'
        from /usr/share/gems/gems/sensu-0.23.2/lib/sensu/api/process.rb:7:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'
        from /usr/share/gems/gems/sensu-0.23.2/exe/sensu-api:7:in `<top (required)>'
        from /usr/bin/sensu-api:23:in `load'
        from /usr/bin/sensu-api:23:in `<main>'

When I manually change version in process.rb I get:

/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- thin_parser (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/gems/gems/thin-1.6.4/lib/thin.rb:39:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/gems/gems/sensu-0.23.2/lib/sensu/api/process.rb:8:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/gems/gems/sensu-0.23.2/exe/sensu-api:7:in `<top (required)>'
        from /usr/bin/sensu-api:23:in `load'
        from /usr/bin/sensu-api:23:in `<main>'

**Comment by cbrown2** [comment]
Updating to 0.24.1 works around this:

http://repositories.sensuapp.org/yum/7/x86_64/
